---
- name: 'Install apt packages'
  apt:
    name:
      - openssh-server
      - ufw
    state: present
    autoclean: true
    autoremove: true
    update_cache: true
  when: ansible_pkg_mgr == 'apt'
  become: true

# vim: ft=yaml.ansible
