---

- name: 'Permit port {{ ssh_port }} through firewalld'
  ansible.posix.firewalld:
    port: '{{ ssh_port }}/tcp'
    state: enabled
    permanent: true
    immediate: true
    offline: true
  become: true

- name: Permit ssh ports from public zone in firewalld
  ansible.posix.firewalld:
    zone: public
    service: ssh
    state: enabled
    permanent: true
    immediate: true
    offline: true
  become: true

- name: Log all firewall denials to `dmesg` and `journalctl -k`
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: 'LogDenied='
    line: 'LogDenied=all'
  notify: reload firewalld
  become: true

# vim: ft=yaml.ansible
