---
- name: Create journald persistence directory
  file:
    state: directory
    path: /var/log/journal
    mode: '700'
  become: true
  notify: restart journald

- name: Enable journald on boot
  systemd:
    name: systemd-journald.service
    enabled: true
    daemon_reload: true
  become: true

# vim: ft=yaml.ansible
