---
- name: Install system dependencies
  include_tasks: '{{ ansible_distribution | lower }}-dependencies.yml'
- name: Update Ansible facts with service information
  service_facts:

- name: Enable EPEL
  include_tasks: epel.yml
  when: ansible_os_family == 'RedHat'

- name: Configure journald
  include_tasks: journald.yml
  when: ansible_service_mgr == 'systemd'

- name: Configure firewalld
  include_tasks: firewalld.yml
  when: ansible_facts.services['firewalld.service'] is defined

- name: Configure UFW
  include_tasks: ufw.yml
  when: ansible_facts.services['ufw.service'] is defined

- import_tasks: automation_access.yml
- import_tasks: sudoers.yml
- import_tasks: sshd.yml
