---
- name: "Create '{{ sudo_group }}' group"
  group:
    name: '{{ sudo_group }}'
    state: present
  become: true

- name: "Allow sudo (with password) to members of '{{ sudo_group }}'"
  lineinfile:
    regexp: '^%{{ sudo_group }} '
    line: '%{{ sudo_group }} ALL=(ALL) ALL'
    path: /etc/sudoers.d/sudo
    validate: '/usr/sbin/visudo -cf %s'
    create: true
    owner: root
    group: root
    mode: '440'
  become: true

# vim: ft=yaml.ansible
