---
- name: Create local 'sudo' group
  group:
    name: sudo
    state: present
  become: true

- name: Set 'sudo' group to allow members to run as root (with password prompt)
  lineinfile:
    regexp: '^%sudo '
    line: '%sudo ALL=(ALL) ALL'
    path: /etc/sudoers.d/sudo
    validate: '/usr/sbin/visudo -cf %s'
    create: true
    owner: root
    group: root
    mode: 0440
  become: true

# vim: ft=yaml.ansible
