---

- name: Set UFW logging
  community.general.ufw:
    logging: 'on'
  become: true

- name: Limit burst SSH auth attempts
  community.general.ufw:
    comment: Limit burst SSH auth attempts to prevent brute force attacks
    rule: limit
    name: ssh
    log: true
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
  # Skip in molecule testing, since containers +
  # kernel modules (iptables) = big problem
  when: not lookup('env', 'MOLECULE_FILE')
  become: true
