---

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
  become: true

- name: restart firewalld
  listen: reload firewalld
  systemd:
    name: firewalld
    state: restarted
  when:
    - ansible_facts.services['firewalld.service'] is defined
    - ansible_facts.services['firewalld.service'].state == 'running'
  become: true

- name: restart sshd
  systemd:
    name: "{{ ansible_facts.services['sshd.service'] is defined | ternary('sshd', 'ssh') }}"
    state: restarted
  become: true

- name: dnf makecache
  listen: update dnf cache
  dnf:
    update_cache: true
  become: true

- name: yum makecache
  listen: update yum cache
  yum:
    update_cache: true
  become: true

- name: apt-cache update
  listen: update apt cache
  apt:
    update_cache: true
  become: true

- name: collect facts
  setup:
