---

- name: restart journald
  service:
    name: systemd-journald
    state: restarted
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  when: |
    (
      ansible_facts.services['firewalld.service'] is defined
    ) and (
      ansible_facts.services['firewalld.service'].state == 'running'
    )
  become: true

- name: restart sshd
  service:
    name: "{{ ansible_facts.services['sshd.service'] is defined | ternary('sshd', 'ssh') }}"
    state: restarted
  become: true

- name: dnf makecache
  listen: update dnf cache
  dnf:
    update_cache: true
  become: true

- name: yum makecache
  listen: update yum cache
  yum:
    update_cache: true
  become: true
