---
dependency:
  name: shell
  command: ansible-galaxy install -r ./requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos-7
    image: docker.io/library/centos:7
    tmpfs:
      - /run
      - /tmp
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
  - name: centos-8
    image: docker.io/library/centos:8
    tmpfs:
      - /run
      - /tmp
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - SYS_ADMIN
    command: /usr/sbin/init
  - name: debian
    image: docker.io/library/debian:10
    tmpfs:
      - /run
      - /tmp
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
provisioner:
  name: ansible
verifier:
  name: ansible
