---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos-8
    image: docker.io/library/centos:8
  - name: centos-7
    image: docker.io/library/centos:7
  - name: debian
    image: docker.io/library/debian:10
provisioner:
  name: ansible
verifier:
  name: ansible
