---
- name: Remove unneeded dnf packages
  dnf:
    name: '{{ python_system.dependencies }}'
    state: absent
  when: ansible_pkg_mgr == 'dnf'
  become: true

- name: Remove unneeded yum packages
  yum:
    name: '{{ python_system.removable_dependencies }}'
    state: absent
  when: ansible_pkg_mgr == 'yum'
  become: true

# vim: ft=yaml.ansible
