---

- name: Include OS-specific vars
  include_vars:
    name: python_system
    file: './dependencies/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'

- name: Install system dependencies
  include_tasks: '{{ ansible_distribution | lower }}-dependencies.yml'

- name: Temp build directory
  file:
    state: directory
    path: /tmp/python-build-dir
    mode: '700'

- name: Check for prior build attempts
  stat:
    path: /tmp/python-build-dir/Python-{{ python_version }}
  register: prior_art

- name: Swap On!
  include_tasks: setup_swap.yml
  vars:
    swap_file: /provisioning_swap_file
    gb_swap_size: 3

- name: Download Python source
  unarchive:
    dest: /tmp/python-build-dir
    remote_src: true
    src: '{{ python_download_url }}'
  when: not prior_art.stat.exists

- name: Configure installer
  command:
    cmd: ./configure --prefix={{ python_prefix | quote }} --enable-optimizations --enable-profiling --with-lto --with-assertions --with-ensurepip=upgrade
    creates: /tmp/python-build-dir/Python-{{ python_version }}/Makefile
  args:
    chdir: /tmp/python-build-dir/Python-{{ python_version }}

- name: 'Compile Python @ {{ python_version }}'
  community.general.make:
    target: all
    chdir: /tmp/python-build-dir/Python-{{ python_version }}

- name: 'Install Python to {{ python_bin_dir }}'
  community.general.make:
    target: install
    chdir: /tmp/python-build-dir/Python-{{ python_version }}
  become: true

- name: Remove build system dependencies
  include_tasks: '{{ ansible_distribution | lower }}-dep-removal.yml'

- name: Cleanup temp dir
  file:
    state: absent
    path: /tmp/python-build-dir
  become: true

- name: Swap Off!
  include_tasks: teardown_swap.yml
  vars:
    swap_file: /provisioning_swap_file
    gb_swap_size: 3


# vim: ft=yaml.ansible
