---

- stat:  # noqa 502
    path: '{{ python_bin }}'
  register: py_path

- name: Python version
  command: '{{ python_bin }} --version'
  when: py_path.stat.exists and py_path.stat.executable
  register: py_version
  changed_when: false

- name: 'Install Python @ {{ python_version }}'
  include_tasks: install.yml
  when: |
    (
      not py_path.stat.exists
    ) or (
      (python_version_major_minor ~ '.') not in py_version.stdout
    )

- stat:  # noqa 502
    path: '{{ python_bin_dir }}/python'
  register: py_path

- name: 'Backfill {{ python_bin_dir }}/python to be {{ python_bin_dir }}/python3'
  file:
    path: '{{ python_bin_dir }}/python'
    src: '{{ python_bin_dir }}/python3'
    state: hard
    owner: root
    group: root
    mode: '755'
  become: true
  when: not py_path.stat.exists
