---
dependency:
  name: shell
  command: ansible-galaxy install -r ./requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: docker.io/library/debian:10
    tmpfs:
      - /run
      - /tmp
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
    groups:
      - packer
provisioner:
  name: ansible
verifier:
  name: ansible
