---
dependency:
  name: shell
  command: ansible-galaxy install -r ./requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: generic/debian10
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
