---
- name: Provision Packer image
  hosts: all

  vars:
    python_version: '3.9.0'

  pre_tasks:
    - name: Alive Check
      ping:
      retries: 5
      delay: 3

  roles:
    - grafeas.os_base
    - thelonelyghost.python
