---
- name: Provision Packer image
  hosts: all

  pre_tasks:
    - name: Alive Check
      ping:
      retries: 5
      delay: 3

  roles:
    - name: grafeas.os_base
    - name: thelonelyghost.python
